# kindly generated by appropriated Rails generator
Mailjet.configure do |config|
  config.api_key = 'b750c46c487ecabccc231de92424673b'
  config.secret_key = 'bbe069a8d54e1684c6b97046af185fa0'
  config.default_from = 'mathieu@dwish.fr'
end
